### PR TITLE
Feature/add networking resources

### PR DESCRIPTION
**Pull request by dzflack**
## TLDR

Add initial support for `Virtual Switch` and `Port Group` resources.

## Still To Do

* General code cleanup
* Add additional components to both vSwitch and PortGroup schemas (i.e. `network_adapters` and `vlan_id`)
* More testing
* Potentially add `update()` functions for resources, depending on additional schema items

### CODE REVIEW

**Comment by josenk** [comment]
Sorry, it's taking a long time for this...   I've been a bit overloaded recently.   I will be able to review soon.  Thanks again for the PR!

**Comment by dzflack** [comment]
No worries; there is still a fair bit more to get this PR ready for merging, so no rush.

**Comment by kidrek** [comment]
Hi josenk, and dzflack. 
I'm working on project using Terraform and Esxi Free. First of all, thank you josenk to share your provider....it's awesome.
I encounter an issue, because i must create network resource.
When do you plan to make your new release available?

**Comment by dzflack** [comment]
Closing due to resources being added in https://github.com/josenk/terraform-provider-esxi/commit/5e1ab94675905bcde6a1435e6f60918fe1881bf2

**Pull request closed without merging**
