### PR TITLE
Terraform 0.12 support

### PR DESCRIPTION
**Pull request by silasb**
Adds support for Go modules as suggested by the terraform devs.

Did not add in vendored files since it's messy and includes a bunch of extra files that aren't needed.

```terraform 0.12upgrade``` command on each example.

### CODE REVIEW

**Comment by josenk** [comment]
Great work!  Thanks for the help.   Looks like modules are back, but this time to stay...  :-)

I'll do some validation, then merge this.

**Comment by josenk** [comment]
Are you sure this is working???

  I upgraded my system to golang 1.12.6, Terraform 0.12.2 and rebuilt.  I cannot make it work.

Using example: 05 Cloudinit and Templates
```
Error: Reference to undeclared resource
  on main.tf line 51, in resource "esxi_guest" "Default":
  51:     userdata.encoding = "gzip+base64"
A managed resource "userdata" "encoding" has not been declared in the root
module.
```

**Comment by silasb** [comment]
I'll give that one a try later this weekend.  I ended up using example 04
and that worked.

—Silas

**Comment by silasb** [comment]
Pushed a new commit, can you check it?  I don't have a CentOS template available, so I couldn't test the `terraform apply` process.

**Pull request merged**
